### ISSUE TITLE
cython + numpy installation problem

### ISSUE THREAD

**Issue by gabrielmontagne** [yxiao1996/pystereogram#1]
There seems to be a strange compatibility issues -- I don't understand it properly -- but perhaps a Cython / Numpy problem? 

![image](https://user-images.githubusercontent.com/95913/222993689-4dfa418a-ec29-478c-8ab4-bb6c4be4e688.png)

**Comment by yxiao1996** [comment]
will take a look. thanks

**Comment by cmahnke** [comment]
This might be related:
```
Collecting pystereogram
  Downloading pystereogram-0.0.20.tar.gz (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.2/118.2 kB 3.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      /private/var/folders/k1/hdlmqrhx72vf59cyh6tkys9h0000gn/T/pip-build-env-c78xomy6/overlay/lib/python3.11/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/k1/hdlmqrhx72vf59cyh6tkys9h0000gn/T/pip-install-ekeyhswm/pystereogram_b04bcee7fefe470bb3ae1b78e3d2e6b8/autostereogram/compute_line.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      import numpy as np
      cimport numpy as np
      DTYPE = np.int64
      ctypedef np.int_t DTYPE_t
               ^
      ------------------------------------------------------------
      
      autostereogram/compute_line.pyx:4:9: 'int_t' is not a type identifier
      Compiling autostereogram/compute_line.pyx because it changed.
      [1/1] Cythonizing autostereogram/compute_line.pyx
      Traceback (most recent call last):
        File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/k1/hdlmqrhx72vf59cyh6tkys9h0000gn/T/pip-build-env-c78xomy6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/k1/hdlmqrhx72vf59cyh6tkys9h0000gn/T/pip-build-env-c78xomy6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/k1/hdlmqrhx72vf59cyh6tkys9h0000gn/T/pip-build-env-c78xomy6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 20, in <module>
        File "/private/var/folders/k1/hdlmqrhx72vf59cyh6tkys9h0000gn/T/pip-build-env-c78xomy6/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/k1/hdlmqrhx72vf59cyh6tkys9h0000gn/T/pip-build-env-c78xomy6/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: autostereogram/compute_line.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Downgrading to NumPy 1.25.2 or 1.26.4 doesn't help...

**Comment by 9021007** [comment]
I am experiencing this as well, py3.11.

**Comment by cmahnke** [comment]
Have a look here:
https://github.com/radames/pystereogram

Maybe this fork fixes the issue
